INSERT INTO IDIOMA (CODIGO, NOMBRE, SALUDO) VALUES ('ES', 'ESPAÑOL', 'HOLA MUNDO');
INSERT INTO IDIOMA (CODIGO, NOMBRE, SALUDO) VALUES ('EN','INGLES','HELLO WORLD');
INSERT INTO IDIOMA (CODIGO, NOMBRE, SALUDO) VALUES ('FR','FRANCES','BONJOUR MONDE');
INSERT INTO IDIOMA (CODIGO, NOMBRE, SALUDO) VALUES ('IT','ITALIANO','CIAO MONDE');